console.log('5>4: ', 5>4);
console.log('"ананас" > "яблоко": ', "ананас" > "яблоко");
console.log('"2" > "12": ', "2" > "12");
console.log('undefined == null: ', undefined == null);
console.log('undefined === null: ', undefined === null);
console.log('null == "\\n0\\n": ', null == "\n0\n");
console.log('null === +"\\n0\\n": ', null === +"\n0\n");
console.log('"" + 1 + 0 ": ', "" + 1 + 0);
console.log('"" - 1 + 0 ": ', "" - 1 + 0);
console.log('true + false: ', true + false);
console.log('6 / "3": ', 6 / "3");
console.log('"2" * "3" : ', "2" * "3" );
console.log('4 + 5 + "px": ',4 + 5 + "px");
console.log('"$" + 4 + 5 : ', "$" + 4 + 5 );
console.log('"4" - 2: ', "4" - 2);
console.log('"4px" - 2 : ', "4px" - 2 );
console.log('7 / 0: ', 7 / 0);
console.log('" -9 " + 5 : ', " -9 " + 5 );
console.log('" -9 " - 5 : ', " -9 " - 5 );
console.log('null + 1 : ', null + 1 );
console.log('undefined + 1 : ', undefined + 1 );
console.log('" \\t \\n" - 2: ', " \t \n" - 2);